#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>
#include <wx/graphics.h>
#include <iostream>
#include <fstream>
#include <vector>
#include <map>
#include <cmath>
#include <utility>
#include <list>
#include <nlohmann/json.hpp>

using json = nlohmann::json;
using namespace std;


class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.
	void panelOnLeftDown(wxMouseEvent& event);
	void panelOnLeftUp(wxMouseEvent& event);
	void panelOnMotion(wxMouseEvent& event);
	void m_panel1OnPaint(wxPaintEvent& event);
	void m_panel1OnUpdateUI(wxUpdateUIEvent& event);
	void draw_line_buttonOnButtonClick(wxCommandEvent& event);
	void draw_curve_buttonOnButtonClick(wxCommandEvent& event);
	void draw_rectangle_buttonOnButtonClick(wxCommandEvent& event);
	void draw_circle_buttonOnButtonClick(wxCommandEvent& event);
	void any_figure_button4OnButtonClick(wxCommandEvent& event);
	void figure_int_circle_button12OnButtonClick(wxCommandEvent& event);
	void figure_sides_choice1OnChoice(wxCommandEvent& event);
	void line_color_button7OnButtonClick(wxCommandEvent& event);
	void save_image_button8OnButtonClick(wxCommandEvent& event);
	void load_image_button9OnButtonClick(wxCommandEvent& event);
	void turn_off_drawing();

public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);
	//// end generated class members
	void draw(wxClientDC & dcClient);
	~GUIMyFrame1();

private:
	wxColour line_colour, filling_colour;
	wxFileDialog * _fileDialog;
	int number_of_sides;

	std::vector<std::list<std::pair<wxPoint, wxColour>>> points;
	bool drawALine;

	std::multimap<wxPoint *, std::pair<float, wxColour>> circles;
	wxPoint begin;	
	bool drawACircle;
	bool isBegin;	

	bool drawARectangle;	
	std::list<std::pair<std::pair<wxPoint *, wxPoint *>, wxColour>> rectangles;

	bool drawingAFigureWithNSides;
	int sidesLeft;	
	std::vector<std::vector<std::pair<wxPoint, wxColour>>> weirdFigures;	

	bool drawAFigureInCircle;	
	std::vector<std::vector<std::pair<wxPoint, wxColour>>> figuresInCircles;
	
	bool drawingABezierCurve;
	std::vector<std::vector<wxPoint>> bezierArray;
	std::vector<wxColour> bezierCurveColors;

	std::vector<wxPoint>::iterator selected;	
};

#endif // __GUIMyFrame1__