#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcbuffer.h>
#include <wx/colordlg.h>
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panel1OnPaint( wxPaintEvent& event );
		void m_panel1OnUpdateUI( wxUpdateUIEvent& event );
		void draw_line_buttonOnButtonClick( wxCommandEvent& event );
		void draw_curve_buttonOnButtonClick( wxCommandEvent& event );
		void draw_rectangle_buttonOnButtonClick( wxCommandEvent& event );
		void draw_circle_buttonOnButtonClick( wxCommandEvent& event );
		void any_figure_button4OnButtonClick( wxCommandEvent& event );
		void figure_int_circle_button12OnButtonClick( wxCommandEvent& event );
		void filling_checkBox1OnCheckBox( wxCommandEvent& event );
		void figure_sides_choice1OnChoice( wxCommandEvent& event );
		void line_color_button7OnButtonClick( wxCommandEvent& event );
		void save_image_button8OnButtonClick( wxCommandEvent& event );
		void figure_color_filling_button10OnButtonClick( wxCommandEvent& event );
		void rotate_figure_button11OnButtonClick( wxCommandEvent& event );
		void move_figure_button12OnButtonClick( wxCommandEvent& event );
		void size_change_button13OnButtonClick( wxCommandEvent& event );
		void load_image_button9OnButtonClick( wxCommandEvent& event );
		void move_wierzcholek_button14OnButtonClick( wxCommandEvent& event );
		void delete_figure_button15OnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void draw(wxClientDC & dcClient);
		~GUIMyFrame1();

	private:
		wxColour line_colour, filling_colour;
		wxImageHandler * image_handler;
		wxFileDialog * _fileDialog;





};

#endif // __GUIMyFrame1__
