#ifndef __GUIMyFrame4__
#define __GUIMyFrame4__

/**
@file
Subclass of MyFrame4, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame4 */
class GUIMyFrame4 : public MyFrame4
{
	protected:
		// Handlers for MyFrame4 events.
		void draw_line_buttonOnButtonClick( wxCommandEvent& event );
		void draw_curve_buttonOnButtonClick( wxCommandEvent& event );
		void draw_rectangle_buttonOnButtonClick( wxCommandEvent& event );
		void any_figure_button4OnButtonClick( wxCommandEvent& event );
		void figure_int_circle_button12OnButtonClick( wxCommandEvent& event );
		void filling_checkBox1OnCheckBox( wxCommandEvent& event );
		void figure_sides_choice1OnChoice( wxCommandEvent& event );
		void line_color_button7OnButtonClick( wxCommandEvent& event );
		void save_image_button8OnButtonClick( wxCommandEvent& event );
		void rotate_figure_button11OnButtonClick( wxCommandEvent& event );
		void move_figure_button12OnButtonClick( wxCommandEvent& event );
		void load_image_button9OnButtonClick( wxCommandEvent& event );
		void delete_figure_button15OnButtonClick( wxCommandEvent& event );

	public:
		/** Constructor */
		GUIMyFrame4( wxWindow* parent );
	//// end generated class members
	
};

#endif // __GUIMyFrame4__
